### ISSUE TITLE
Upload failing

### ISSUE THREAD

**Issue by thematrix1337** [kannibalox/PtpUploader#37]
Hello, i get the following error/stacktrace when trying to upload a file
```
2023-11-22 20:12:01,323 INFO  werkzeug    127.0.0.1 - - [22/Nov/2023 20:12:01] "GET /static/source_icon/file.ico HTTP/1.1" 200 -
2023-11-22 20:12:02,445 DEBUG [imdbpy] /home/user/.local/lib/python3.9/site-packages/imdb/__init__.py:840: retrieving "plot" info set
2023-11-22 20:12:02,445 DEBUG [imdbpy.parser.http] /home/user/.local/lib/python3.9/site-packages/imdb/parser/http/__init__.py:391: fetching url https://www.imdb.com/title/*****/plotsummary (size: -1)
2023-11-22 20:12:03,861 INFO  PtpUploader.Job.Supervisor Launching upload job for 1
2023-11-22 20:12:03,865 INFO  PtpUploader.release_extractor Source is a single file, skipping extraction
[] []
[]
2023-11-22 20:12:03,868 ERROR PtpUploader.Job.WorkerBase Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/PtpUploader/Job/WorkerBase.py", line 74, in Work
    self.__WorkInternal()
  File "/home/user/.local/lib/python3.9/site-packages/PtpUploader/Job/WorkerBase.py", line 45, in __WorkInternal
    phase()
  File "/home/user/.local/lib/python3.9/site-packages/PtpUploader/Job/Upload.py", line 271, in __MakeReleaseDescription
    releaseDescriptionFormatter = ReleaseDescriptionFormatter(
  File "/home/user/.local/lib/python3.9/site-packages/PtpUploader/ReleaseDescriptionFormatter.py", line 60, in __init__
    self.__GetMediaInfo()
  File "/home/user/.local/lib/python3.9/site-packages/PtpUploader/ReleaseDescriptionFormatter.py", line 175, in __GetMediaInfo
    self.__GetMediaInfoHandleOther()
  File "/home/user/.local/lib/python3.9/site-packages/PtpUploader/ReleaseDescriptionFormatter.py", line 154, in __GetMediaInfoHandleOther
    self.MainMediaInfo = mediaInfos[0]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/PtpUploader/Job/WorkerBase.py", line 74, in Work
    self.__WorkInternal()
  File "/home/user/.local/lib/python3.9/site-packages/PtpUploader/Job/WorkerBase.py", line 45, in __WorkInternal
    phase()
  File "/home/user/.local/lib/python3.9/site-packages/PtpUploader/Job/Upload.py", line 271, in __MakeReleaseDescription
    releaseDescriptionFormatter = ReleaseDescriptionFormatter(
  File "/home/user/.local/lib/python3.9/site-packages/PtpUploader/ReleaseDescriptionFormatter.py", line 60, in __init__
    self.__GetMediaInfo()
  File "/home/user/.local/lib/python3.9/site-packages/PtpUploader/ReleaseDescriptionFormatter.py", line 175, in __GetMediaInfo
    self.__GetMediaInfoHandleOther()
  File "/home/user/.local/lib/python3.9/site-packages/PtpUploader/ReleaseDescriptionFormatter.py", line 154, in __GetMediaInfoHandleOther
    self.MainMediaInfo = mediaInfos[0]
IndexError: list index out of range
2023-11-22 20:12:03,872 INFO  PtpUploader.Job.Supervisor running: [], waiting: [], done: [1]
2023-11-22 20:12:06,872 INFO  PtpUploader.Job.Supervisor Job 1 finished with exception 'list index out of range'
```

**Comment by kannibalox** [comment]
This would seem to indicate that the single file being used isn't providing a proper mediainfo. Can you please post the output of the mediainfo command for that file?

**Comment by thematrix1337** [comment]
Mediainfo
`
General
Complete name                            : ******.mkv
Format                                   : Matroska
Format version                           : Version 4
File size                                : 1.88 GiB
Duration                                 : 1 h 33 min
Overall bit rate                         : 2 878 kb/s
Encoded date                             : UTC 2023-03-30 20:19:12
Writing application                      : mkvmerge v75.0.0 ('Goliath') 64-bit
Writing library                          : libebml v1.4.4 + libmatroska v1.7.1

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L5
Format settings                          : CABAC / 5 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 5 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 1 h 33 min
Bit rate                                 : 2 782 kb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 29.970 (29970/1000) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.045
Stream size                              : 1.80 GiB (96%)
Writing library                          : x264 core 164
Encoding settings                        : cabac=1 / ref=6 / deblock=1:0:0 / analyse=0x3:0x111 / me=hex / subme=7 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=4 / lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / stitchable=1 / constrained_intra=0 / bframes=16 / b_pyramid=1 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=60 / keyint_min=20 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=abr / mbtree=1 / bitrate=2782 / ratetol=1.0 / qcomp=0.60 / qpmin=10 / qpmax=50 / qpstep=4 / vbv_maxrate=4000 / vbv_bufsize=8000 / nal_hrd=none / filler=0 / ip_ratio=1.41 / aq=1:1.00
Default                                  : No
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.601 PAL
Transfer characteristics                 : BT.470 System B/G
Matrix coefficients                      : BT.470 System B/G

Audio
ID                                       : 2
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : A_AAC-2
Duration                                 : 1 h 33 min
Bit rate                                 : 126 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 44.1 kHz
Frame rate                               : 43.066 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 84.0 MiB (4%)
Default                                  : No
Forced                                   : No
`
