### ISSUE TITLE
Unable to use ffmpeg instead of mpv

### ISSUE THREAD

**Issue by newadventure079** [kannibalox/PtpUploader#9]
I set 
```
mpv:
    path:
```
in the config.yml so I can use ffmpeg but I can't get PtpUploader to accept ffmpeg and not mpv

```
Traceback (most recent call last):
  File "/Users/Documents/code/projects/PtpUploader/src/PtpUploader/ReleaseInfoMaker.py", line 164, in <module>
    run()
  File "/Users/Documents/code/projects/PtpUploader/src/PtpUploader/ReleaseInfoMaker.py", line 158, in run
    releaseInfoMaker.MakeReleaseInfo(
  File "/Users/Documents/code/projects/PtpUploader/src/PtpUploader/ReleaseInfoMaker.py", line 125, in MakeReleaseInfo
    self.SaveReleaseDescripionFile(
  File "/Users/Documents/code/projects/PtpUploader/src/PtpUploader/ReleaseInfoMaker.py", line 85, in SaveReleaseDescripionFile
    releaseDescriptionFormatter = ReleaseDescriptionFormatter(
  File "/opt/homebrew/lib/python3.10/site-packages/PtpUploader/ReleaseDescriptionFormatter.py", line 54, in __init__
    self.__TakeAndUploadScreenshots()
  File "/opt/homebrew/lib/python3.10/site-packages/PtpUploader/ReleaseDescriptionFormatter.py", line 138, in __TakeAndUploadScreenshots
    screenshotMaker = ScreenshotMaker(logger, path)
  File "/opt/homebrew/lib/python3.10/site-packages/PtpUploader/Tool/ScreenshotMaker.py", line 53, in __init__
    if shutil.which(Settings.MpvPath):
  File "/opt/homebrew/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shutil.py", line 1401, in which
    if os.path.dirname(cmd):
  File "/opt/homebrew/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

And if I set 
```
  #mpv:
  #  path: 
```
 I get
```
Traceback (most recent call last):
  File "/Users/Documents/code/projects/PtpUploader/src/PtpUploader/ReleaseInfoMaker.py", line 7, in <module>
    django.setup()
  File "/opt/homebrew/lib/python3.10/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/opt/homebrew/lib/python3.10/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/opt/homebrew/lib/python3.10/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/homebrew/lib/python3.10/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/opt/homebrew/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/homebrew/lib/python3.10/site-packages/PtpUploader/web/settings.py", line 20, in <module>
    Settings.LoadSettings()
  File "/opt/homebrew/lib/python3.10/site-packages/PtpUploader/Settings.py", line 125, in LoadSettings
    Settings.MpvPath = config.tools.mpv.path
  File "/opt/homebrew/lib/python3.10/site-packages/dynaconf/utils/boxing.py", line 16, in evaluate
    value = f(dynabox, item, *args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/dynaconf/utils/boxing.py", line 39, in __getattr__
    return super(DynaBox, self).__getattr__(n_item, *args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/dynaconf/vendor/box/box.py", line 177, in __getattr__
    raise BoxKeyError(str(E)) from _A
dynaconf.vendor.box.exceptions.BoxKeyError: "'DynaBox' object has no attribute 'MPV'"
```

The command was `python3 /Users/Documents/code/projects/PtpUploader/src/PtpUploader/ReleaseInfoMaker.py --notorrent /Volumes/data/LTS/Movies/movie.avi`

**Comment by kannibalox** [comment]
Try setting `screenshot_tool` to force a specific one:
```
tools:
  # Only one of mpv, ffmpeg or mplayer is required. mpv is preferred, but PtpUploader will attempt to auto-detect
  # whichever one is available.
  screenshot_tool: auto
  # leave the rest as default
```
The user experience can definitely be improved there though, i'll see about making that better.

**Comment by newadventure079** [comment]
Ah, ya that worked!

**Comment by daomengRen** [comment]
> Ah, ya that worked!

Hello, newadventure079, are you running on docker or general Linux, I want to ask some questions, can you tell me how to contact you, such as email or discord, etc. kannibalox is updating the project frequently, I don't want to disturb him, do you have time to help me, look forward to your reply, thank you

**Comment by kannibalox** [comment]
Please consider using the PTP thread linked in the README. It'll allow for more people to help with both reporting issues and finding solutions.
